CREATE DATABASE exercise;
USE exercise;
CREATE TABLE KHACHHANG(
	MAKH INT NOT NULL,
    HOTEN VARCHAR(30) NOT NULL,
    DCHI VARCHAR(30),
    SODT VARCHAR(30),
    NGSINH DATETIME,
    DOANHSO FLOAT DEFAULT 0,
    NGDK DATETIME,
    PRIMARY KEY(MAKH)
);
CREATE TABLE NHANVIEN(
	MANV INT NOT NULL,
    HOTEN VARCHAR(30) NOT NULL,
    NGVL DATETIME,
    SODT VARCHAR(30),
    PRIMARY KEY(MANV)
);
CREATE TABLE SANPHAM(
	MASP INT NOT NULL,
    TENSP VARCHAR(30) NOT NULL,
    DVT INT DEFAULT 0,
    NUOCSX VARCHAR(30) DEFAULT 'VIETNAM',
    GIA FLOAT DEFAULT 0,
    PRIMARY KEY(MASP)
);
CREATE TABLE HOADON(
	SOHD INT NOT NULL,
    NGHD DATETIME,
    MAKH INT,
    MANV INT,
    TRIGIA FLOAT DEFAULT 0,
    PRIMARY KEY(SOHD),
    FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
);
CREATE TABLE CTHD(
	SOHD INT,
    MASP INT,
    SL INT DEFAULT 0,
    FOREIGN KEY(SOHD) REFERENCES HOADON(SOHD),
    FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP)
);

-- triggle
DELIMITER $$
CREATE TRIGGER UpdateDoanhSo
AFTER INSERT ON HOADON
FOR EACH ROW
BEGIN
    UPDATE KHACHHANG
    SET DOANHSO = DOANHSO + NEW.TRIGIA
    WHERE MAKH = NEW.MAKH;
END $$

DELIMITER $$
CREATE TRIGGER UpdateTongGiaTriHoaDon
AFTER INSERT ON CTHD
FOR EACH ROW
BEGIN
    UPDATE HOADON
    SET TRIGIA = TRIGIA + (NEW.SL * (SELECT GIA FROM SANPHAM WHERE MASP = NEW.MASP))
    WHERE SOHD = NEW.SOHD;
END $$

DELIMITER $$
CREATE TRIGGER UpdateSanPham
AFTER INSERT ON CTHD
FOR EACH ROW
BEGIN
    UPDATE SANPHAM
    SET DVT = DVT - NEW.SL
    WHERE MASP = NEW.MASP;
END $$
-- triggle

-- 1.Có bao nhiêu sản phẩm khác nhau được bán ra trong năm 2006.
SELECT SANPHAM.* 
FROM SANPHAM
JOIN CTHD ON CTHD.MASP = SANPHAM.MASP
JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
WHERE YEAR(HOADON.NGHD) = 2006; 

-- 2.Cho biết trị giá hóa đơn cao nhất, thấp nhất là bao nhiêu ?
SELECT MAX(HOADON.TRIGIA) AS MAXTRIGIA
FROM HOADON;
SELECT MIN(HOADON.TRIGIA) AS MINTRIGIA
FROM HOADON;

-- 3.Trị giá trung bình của tất cả các hóa đơn được bán ra trong năm 2006 là bao nhiêu?
SELECT AVG(HOADON.TRIGIA) AS TRIGIATB
FROM HOADON
WHERE YEAR(HOADON.NGHD) = 2006;

-- 4.Tính doanh thu bán hàng trong năm 2006.
SELECT SUM(HOADON.TRIGIA) AS SUMTRIGIA
FROM HOADON
WHERE YEAR(HOADON.NGHD) = 2006;

-- 5.Tìm số hóa đơn có trị giá cao nhất trong năm 2006.
SELECT MAX(HOADON.TRIGIA) MAXTRIGIA
FROM HOADON
WHERE YEAR(HOADON.NGHD) = 2006;

-- 6.Tìm họ tên khách hàng đã mua hóa đơn có trị giá cao nhất trong năm 2006.
SELECT KHACHHANG.* 
FROM KHACHHANG
JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
WHERE HOADON.TRIGIA = 
(SELECT MAX(HOADON.TRIGIA) MAXTRIGIA
FROM HOADON
WHERE YEAR(HOADON.NGHD) = 2006);

-- 7.In ra danh sách 3 khách hàng (MAKH, HOTEN) có doanh số cao nhất.
SELECT KHACHHANG.MAKH, KHACHHANG.HOTEN
FROM KHACHHANG
ORDER BY KHACHHANG.DOANHSO DESC
LIMIT 3;

-- 8.In ra danh sách các sản phẩm (MASP, TENSP) có giá bán bằng 1 trong 3 mức giá cao nhất.
SELECT MASP, TENSP
FROM SANPHAM
WHERE GIA IN ( SELECT GIA FROM
  (SELECT DISTINCT GIA
  FROM SANPHAM
  ORDER BY GIA DESC
  LIMIT 3) AS LISTGIA
)
ORDER BY GIA DESC;

SELECT MASP, TENSP
FROM SANPHAM
WHERE GIA IN ((SELECT MAX(GIA) FROM SANPHAM), 
				(SELECT MAX(GIA) FROM SANPHAM WHERE GIA < (SELECT MAX(GIA) FROM SANPHAM)),	
                (SELECT MAX(GIA) FROM SANPHAM WHERE GIA < (SELECT MAX(GIA) FROM SANPHAM WHERE GIA < (SELECT MAX(GIA) FROM SANPHAM))))
ORDER BY GIA DESC;

-- 9.In ra danh sách các sản phẩm (MASP, TENSP) do “Thai Lan” sản xuất 
-- có giá bằng 1 trong 3 mức giá cao nhất (của tất cả các sản phẩm).
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'Thai Lan' AND GIA IN ((SELECT MAX(GIA) FROM SANPHAM), 
				(SELECT MAX(GIA) FROM SANPHAM WHERE GIA < (SELECT MAX(GIA) FROM SANPHAM)),	
                (SELECT MAX(GIA) FROM SANPHAM WHERE GIA < (SELECT MAX(GIA) FROM SANPHAM WHERE GIA < (SELECT MAX(GIA) FROM SANPHAM))))
ORDER BY GIA DESC;

-- 10.In ra danh sách các sản phẩm (MASP, TENSP) do “Trung Quoc” sản xuất 
-- có giá bằng 1 trong 3 mức giá cao nhất (của sản phẩm do “Trung Quoc” sản xuất).
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc' AND GIA IN ((SELECT MAX(GIA) FROM SANPHAM WHERE NUOCSX = 'Trung Quoc'), 
				(SELECT MAX(GIA) FROM SANPHAM WHERE NUOCSX = 'Trung Quoc' AND GIA < (SELECT MAX(GIA) FROM SANPHAM WHERE NUOCSX = 'Trung Quoc')),	
                (SELECT MAX(GIA) FROM SANPHAM WHERE NUOCSX = 'Trung Quoc' AND GIA < (SELECT MAX(GIA) FROM SANPHAM WHERE NUOCSX = 'Trung Quoc' AND GIA < (SELECT MAX(GIA) FROM SANPHAM WHERE NUOCSX = 'Trung Quoc'))))
ORDER BY GIA DESC;

-- 11.* In ra danh sách 3 khách hàng có doanh số cao nhất (sắp xếp theo kiểu xếp hạng).
SELECT SubQuery.MAKH, SubQuery.HOTEN, SubQuery.DoanhSo
FROM (SELECT KHACHHANG.MAKH,KHACHHANG.HOTEN, KHACHHANG.DoanhSo
FROM KHACHHANG
ORDER BY KHACHHANG.DOANHSO DESC
LIMIT 3) AS SubQuery
ORDER BY SubQuery.DoanhSo;

-- 12.Tính tổng số sản phẩm do “Trung Quoc” sản xuất.
SELECT SUM(DVT)
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc';

-- 13.Tính tổng số sản phẩm của từng nước sản xuất.
SELECT SANPHAM.NUOCSX, SUM(DVT)
FROM SANPHAM
GROUP BY SANPHAM.NUOCSX;

-- 14.Với từng nước sản xuất, tìm giá bán cao nhất, thấp nhất, trung bình của các sản phẩm.
SELECT NUOCSX, MAX(GIA), MIN(GIA), AVG(GIA)
FROM SANPHAM
GROUP BY NUOCSX;

-- 15.Tính doanh thu bán hàng mỗi ngày.
SELECT HOADON.NGHD, SUM(SL * GIA) AS DOANHSO
FROM HOADON
JOIN CTHD ON HOADON.SOHD = CTHD.SOHD
JOIN SANPHAM ON CTHD.MASP = SANPHAM.MASP
GROUP BY NGHD;

-- 16.Tính tổng số lượng của từng sản phẩm bán ra trong tháng 10/2006.
SELECT MASP, SUM(SL) AS TONG_SL
FROM HOADON
JOIN CTHD ON HOADON.SOHD = CTHD.SOHD
WHERE NGHD BETWEEN '2006-10-01' AND '2006-10-31'
GROUP BY MASP;

-- 17.Tính doanh thu bán hàng của từng tháng trong năm 2006.
SELECT MONTH(NGHD) AS THANG, SUM(TRIGIA) AS DOANHSO
FROM HOADON
WHERE YEAR(NGHD) = 2006
GROUP BY THANG;

-- 18.Tìm hóa đơn có mua ít nhất 4 sản phẩm khác nhau.
SELECT HOADON.SOHD, COUNT(DISTINCT SANPHAM.MASP) AS SO_SP_KHAC_NHAU
FROM HOADON
JOIN CTHD ON CTHD.SOHD = HOADON.SOHD
JOIN SANPHAM ON CTHD.MASP = SANPHAM.MASP
GROUP BY HOADON.SOHD
HAVING COUNT(DISTINCT SANPHAM.MASP) >= 4;

-- 19.Tìm hóa đơn có mua 3 sản phẩm do “Viet Nam” sản xuất (3 sản phẩm khác nhau).
SELECT HOADON.SOHD, COUNT(DISTINCT SANPHAM.MASP) AS SO_SP_KHAC_NHAU
FROM HOADON
JOIN CTHD ON CTHD.SOHD = HOADON.SOHD
JOIN SANPHAM ON CTHD.MASP = SANPHAM.MASP
WHERE SANPHAM.NUOCSX = 'Viet Nam'
GROUP BY HOADON.SOHD
HAVING COUNT(DISTINCT SANPHAM.MASP) >= 3;

-- 20.Tìm khách hàng (MAKH, HOTEN) có số lần mua hàng nhiều nhất.
SELECT KHACHHANG.*, COUNT(HOADON.SOHD) AS SOLANMUA
FROM KHACHHANG
JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
GROUP BY KHACHHANG.MAKH
HAVING  SOLANMUA >=  ALL (SELECT COUNT(HOADON.SOHD) AS SO_LAN_MUA_MAX
						FROM HOADON
						GROUP BY HOADON.MAKH);

-- 21.Tháng mấy trong năm 2006, doanh số bán hàng cao nhất ?
SELECT MONTH(NGHD) AS THANG, SUM(TRIGIA) AS DOANHSO
FROM HOADON
GROUP BY THANG
HAVING DOANHSO >= ALL(SELECT SUM(TRIGIA)
						FROM HOADON
						WHERE YEAR(NGHD) = 2006
						GROUP BY MONTH(NGHD));
                        
-- 22.Tìm sản phẩm (MASP, TENSP) có tổng số lượng bán ra thấp nhất trong năm 2006.
SELECT SANPHAM.MASP, SANPHAM.TENSP, SUM(CTHD.SL) AS MINTONGSL
FROM SANPHAM
JOIN CTHD ON CTHD.MASP = SANPHAM.MASP
JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
WHERE YEAR(HOADON.NGHD) = 2006
GROUP BY SANPHAM.MASP, SANPHAM.TENSP
HAVING SUM(CTHD.SL) <= ALL(SELECT SUM(CTHD.SL)
							FROM SANPHAM
							JOIN CTHD ON CTHD.MASP = SANPHAM.MASP
							JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
							WHERE YEAR(HOADON.NGHD) = 2006
                            GROUP BY SANPHAM.MASP, SANPHAM.TENSP);

-- 23.*Mỗi nước sản xuất, tìm sản phẩm (MASP,TENSP) có giá bán cao nhất.
SELECT s1.MASP, s1.TENSP, s1.NUOCSX, s1.GIA
FROM SANPHAM s1
WHERE s1.GIA = (
    SELECT MAX(s2.GIA)
    FROM SANPHAM s2
    WHERE s1.NUOCSX = s2.NUOCSX
);

-- 24.Tìm nước sản xuất sản xuất ít nhất 3 sản phẩm có giá bán khác nhau.
SELECT SANPHAM.NUOCSX, COUNT(DISTINCT GIA)
FROM SANPHAM
GROUP BY SANPHAM.NUOCSX
HAVING COUNT(DISTINCT GIA) >= 3;

-- 25.*Trong 10 khách hàng có doanh số cao nhất,
-- tìm khách hàng có số lần mua hàng nhiều nhất.
SELECT LISTKH.MAKH, LISTKH.HOTEN, COUNT(HOADON.SOHD) AS SOLANMUA
FROM (SELECT KHACHHANG.MAKH, KHACHHANG.HOTEN FROM KHACHHANG
		ORDER BY KHACHHANG.DOANHSO DESC
		LIMIT 10) AS LISTKH
JOIN HOADON ON LISTKH.MAKH = HOADON.MAKH
GROUP BY LISTKH.MAKH
HAVING  SOLANMUA >=  ALL (SELECT COUNT(HOADON.SOHD) AS SO_LAN_MUA_MAX
						FROM HOADON
						GROUP BY HOADON.MAKH);
                                             

                   






