CREATE DATABASE ERD;
USE ERD;
CREATE TABLE PHIEUXUAT(
	SoPX INT PRIMARY KEY AUTO_INCREMENT,
    NgayXuat DATETIME
);

CREATE TABLE VATTU(
	MaVTU INT PRIMARY KEY AUTO_INCREMENT,
    TenVTU VARCHAR(255) NOT NULL
);

CREATE TABLE CTPHIEUXUAT(
	DGXuat FLOAT NOT NULL,
    SLXuat INT NOT NULL,
    SoPX INT,
    FOREIGN KEY(SoPX) REFERENCES PHIEUXUAT(SoPX),
    MaVTU INT,
    FOREIGN KEY(MaVTU) REFERENCES VATTU(MaVTU)
);

CREATE TABLE PHIEUNHAP(
	SoPN INT PRIMARY KEY AUTO_INCREMENT,
    NgayNhap DATETIME
);

CREATE TABLE CTPHIEUNHAP(
	DGNhap FLOAT NOT NULL,
    SLNhap INT NOT NULL,
    SoPN INT,
    FOREIGN KEY(SoPN) REFERENCES PHIEUNHAP(SoPN),
    MaVTU INT,
    FOREIGN KEY(MaVTU) REFERENCES VATTU(MaVTU)
);

CREATE TABLE CTDONDH(
	SoDH INT,
    MaVTU INT,
    FOREIGN KEY(SoDH) REFERENCES DONDH(SoDH),
    FOREIGN KEY(MaVTU) REFERENCES VATTU(MaVTU)
);

CREATE TABLE NHACC(
	MaNCC INT PRIMARY KEY AUTO_INCREMENT,
    TenNCC VARCHAR(255) NOT NULL,
    DiaChi VARCHAR(255) NOT NULL,
    SDT VARCHAR(255) NOT NULL
);

CREATE TABLE DONDH(
	SoDH INT PRIMARY KEY AUTO_INCREMENT,
    NgayDH DATETIME,
    MaNCC INT,
    FOREIGN KEY(MaNCC) REFERENCES NHACC(MaNCC)
);

