CREATE DATABASE QuanLyBanHang;
USE QuanLyBanHang;
CREATE TABLE Customer(
	cID INT PRIMARY KEY AUTO_INCREMENT,
    cName VARCHAR(255) NOT NULL,
    cAge INT NOT NULL CHECK(cAge >= 18)
);
CREATE TABLE Product(
	pID INT PRIMARY KEY AUTO_INCREMENT,
    pName VARCHAR(255) NOT NULL,
    pPrice FLOAT NOT NULL
);
CREATE TABLE Orders(
	oID INT PRIMARY KEY AUTO_INCREMENT,
    cID INT,
    oDate DATETIME,
    oTotalPrice FLOAT,
    FOREIGN KEY(cID) REFERENCES Customer(cID)
);

CREATE TABLE OrderDetail(
	oID INT,
    pID INT,
    odQTY INT NOT NULL,
    FOREIGN KEY(oID) REFERENCES Orders(oID),
    FOREIGN KEY(pID) REFERENCES Product(pID)
);
